language: python
sudo: false
matrix:
  include:
  - python: 2.7
    env: TOXENV=py27,codecov
  - python: 3.6
    env: TOXENV=py36,codecov,lint
  - python: pypy
    env: TOXENV=pypy
  - python: pypy3
    env: TOXENV=pypy3
install:
- pip install -U pip tox
script:
- tox
deploy:
  provider: pypi
  user: cfhamlet
  script: pip install --upgrade setuptools wheel
  password:
    secure: q8V62BMMHiJjjcw2pVG9UGfWoJcQML/vl3Z7ehhwp0J+OhL4cRXMAld5C2yFT4NOH+Zw7fKv6OFl15I8LTcVT4pJHmw6MXN1t4po3cvVjR2Icqy5hnidIMdmGgW54/+vdB82VOVYw8ny9Hoo1TU4i2xkEg6VoBtiWmH27BLFahubHuWkuWsOKBlarDmRcTGlT9EiPJnE/6mwTcNPvMtZMOPsn/E6sX+WGtfSfR1lwS+dlKKbey6sNj6xvxyt2jcATk+ha9BZw7GrulsjzgzsgV4eOE57zfCIlrwJ34nocS8PBE9OlpSv5LMqcduGM2Dm0Vg9cRUlywEeuYcxt7J4CCAKIE+KURHqpDvC7Ac+TV2uKf5OoyUQDNC9lxc98IOfxHFftv+VjiqQ51Yx5QkK8vAfiCYR1JyJx/RcyfXD0TqY66xPDvoDFchFNYKMC+Kn5OkOIDo+Zabi/JZACDqgdPuV3PvxV8H2QUX7x4sH9jN3d4SiYAjqemNjYX5kBU/rBSvfIezShT3BJ0Ql26IYK9rAysez1GRGs1Rc6wPOy2zksUlFMuINn4D6ofFGZpN0GmL+m/D8nRlRQ8d1niICaGdLCGjPaJDaSbWu1p3lx/Vd/azchbcS8DpnmAZLnvQYJB9i4/F0+mnfOOzT8Vg9S+5uqojYh8Kk9VjAJUv9/3I=
  true:
    tags: true
    condition: ${TRAVIS_PYTHON_VERSION} == 2.7
