language: python
sudo: false
matrix:
  include:
  - python: 2.7
    env: TOXENV=py27,codecov
  - python: 3.6
    env: TOXENV=py36,codecov,lint
  - python: pypy
    env: TOXENV=pypy
  - python: pypy3
    env: TOXENV=pypy3
install:
- pip install -U pip tox
script:
- tox
deploy:
  provider: pypi
  user: cfhamlet
  script: pip install --upgrade setuptools wheel
  password:
    secure: NvEMhJZzHsV665KuB5Pa8xoQbRv/wpvj6OAQN7greOFPQSpw84EgAT2HSKR/B/L4/V/Phhf1ucEqHTDTyHG36ixHPkGnDAndWi0sQ5/nbgylvlZcMo8klPaF+RsS1NLR3Wr11j5AqMq1ni5fwuNewmhVdrfhDWzVmM3MAWPUCw0Pk37Pvszbx9uVQyGa0As3hgLwDU3UiIZp6I5v7eyxPpgfnAM8BRnis70m1i4LGlTVYbafycWJFK55W0drMTvQ9vzkFGWze6ONuAp9Jx/7+5sX6soy50Wfbs9O7E+DsuD35ejU74Ayo9GEA8+mFHP5hrqONqo08c4IOXXHomKAkocfRkjyJyCSB9aarjS/+0NNZC1v93Wi2JhPJNyoOA7U7dvm3FvBPXv63FWOu9VoJ2PMJYEnnuXvE5iir7ixlglZfkdEml0xe7USXiQYg22pIUhSviqSIwZDUrhR7T3GAtWBsgdqO9DqtDXDDokMjKM0BndvihBXO+FU5JNxqA45H3pVWqlVuJcsoN17oW0duqyQbd97orNbDosv3lmdNwx664w+k3bn0G8bhygDSO7UVBC+qlBvWnLsUXYHQ9dWRUDIsMHJWyzlim/rnEX883USbLQ/yEdocu67HB921aQUPaBSFVR6O46QmfI8aLjwhITWX59/Dqu4fFN5guypjSY=
  true:
    tags: true
    condition: ${TRAVIS_PYTHON_VERSION} == 2.7
